import streamlit as st
from ollama import Client

# Configure the page
st.set_page_config(page_title="LLM Chat", page_icon="🤖", layout="centered")
st.title("🤖 My Remote LLM Chatbot")

# 1. Sidebar Configuration
st.sidebar.header("Connection Settings")

# Paste your active public URL generated by your ngrok script here
NGROK_URL = st.sidebar.text_input(
    "API Endpoint URL",
    value="https://evident-lens-surpass.ngrok-free.dev",
)

# 2. Initialize the Ollama Client pointing to ngrok
@st.cache_resource
def get_ollama_client(url):
    return Client(host=url)

client = get_ollama_client(NGROK_URL)

# 💡 NEW: Fetch the list of models actively running on your remote Ollama server
@st.fragment # Keeps the model refreshing isolated so it doesn't break chat flow
def get_available_models():
    try:
        model_list_data = client.list()
        # Extract model names from the response object
        models = [model.model for model in model_list_data.models]
        return models
    except Exception as e:
        st.sidebar.error(f"Could not fetch models: {e}")
        # Fallback list if the connection drops or is initializing
        return ["gemma2:2b", "llama3.2"]

# Fetch active models
available_models = get_available_models()

# Model Selection Dropdown populated dynamically
MODEL_NAME = st.sidebar.selectbox(
    "Select Model Name",
    options=available_models,
    index=0  # Default selection to the first available model
)

# 3. Initialize chat history in session state
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display prior chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# 4. Accept user input
if user_input := st.chat_input("Ask something..."):
    # Display user message
    with st.chat_message("user"):
        st.markdown(user_input)
    st.session_state.messages.append({"role": "user", "content": user_input})

    # Generate and display assistant response
    with st.chat_message("assistant"):
        with st.spinner(f"Thinking ({MODEL_NAME})..."):
            try:
                # Query using the working Client SDK approach
                response = client.chat(
                    model=MODEL_NAME,
                    messages=st.session_state.messages
                )
                response_text = response['message']['content']
                st.markdown(response_text)
                
            except Exception as e:
                response_text = f"❌ Error communicating with LLM: {e}"
                st.error(response_text)

    st.session_state.messages.append(
        {"role": "assistant", "content": response_text}
    )
