import streamlit as st
from ollama import Client

# Configure the page
st.set_page_config(page_title="LLM Chat", page_icon="🤖", layout="centered")
st.title("🤖 My Remote LLM Chatbot")

# 1. Sidebar Configuration
# Paste your active public URL generated by your ngrok script here
NGROK_URL = st.sidebar.text_input(
    "API Endpoint URL",
    value="https://evident-lens-surpass.ngrok-free.dev",
)

MODEL_NAME = st.sidebar.text_input("Model Name", value="llama3.2")

# 2. Initialize the Ollama Client pointing to ngrok
# The SDK automatically targets the right endpoints if given the base URL
@st.cache_resource
def get_ollama_client(url):
    return Client(host=url)

client = get_ollama_client(NGROK_URL)

# 3. Initialize chat history in session state
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display prior chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# 4. Accept user input
if user_input := st.chat_input("Ask something..."):
    # Display user message
    with st.chat_message("user"):
        st.markdown(user_input)
    st.session_state.messages.append({"role": "user", "content": user_input})

    # Generate and display assistant response
    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                # Query using the working Client SDK approach
                response = client.chat(
                    model=MODEL_NAME,
                    messages=st.session_state.messages
                )
                response_text = response['message']['content']
                st.markdown(response_text)
                
            except Exception as e:
                response_text = f"❌ Error communicating with LLM: {e}"
                st.error(response_text)

    st.session_state.messages.append(
        {"role": "assistant", "content": response_text}
    )
